#!/usr/bin/python2.7


print "Taking values "
def enumerate_moves(x, y):

    potential_moves = []     # Intializing empty list
    print "starts the gaming ", x , y
     # resolve knight moves. 8 possible moves maximally
    #if board[x][y] == "bKnight":
    if xy == "d2":
        print"Entered into Knight piece " 
        potential_moves.append([[x+2], [y+1]])
        potential_moves.append([[x+2], [y-1]])
        potential_moves.append([[x+1], [y+2]])
        potential_moves.append([[x+1], [y-2]])
        potential_moves.append([[x-2], [y-1]])
        potential_moves.append([[x-2], [y+1]])
        potential_moves.append([[x-1], [y+2]])
        potential_moves.append([[x-1], [y-2]])

        moves = append_strip_negatives(potential_moves)
        return moves
        print moves

enumerate_moves("d", 2)        
